config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  root 'contacts#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :first_name, :last_name, :number, presence: true
  validates :number, format: { with: /\A(\d+)\z/ }
  validates :number, length: { in: 10..13 }

  scope :search, ->(search_regexp, search_digits){ where('first_name REGEXP ? or last_name REGEXP ? or number like ?', search_regexp, search_regexp, "%#{search_digits}%") }

  def self.prepare_search_regexp(query_params)
    search_regexp = ''
    query_params.chars.each do |digit|
      search_regexp << regexp_group_for(digit)
    end
    search_regexp
  end

  def self.regexp_group_for(digit)
    PHONE_KEYPAD_ALPHABETS[:"#{digit}"]
  end

  def self.perform_search(query_params)
    search_regexp = prepare_search_regexp(query_params)
    self.search(search_regexp, query_params)
  end

  def display_full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = params.fetch(:q, {})[:search].present? ? Contact.perform_search(params[:q][:search]) : Contact.all
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<tr class="info text-center" data-id='<%=contact.id%>'>
  <td><p data-class="contact-name"><%= link_to contact.display_full_name, contact_path(contact) %></p>
  <p data-class="contact-number"><%= contact.number %></p></td>
</tr>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/_search_form.html.erb
<div class="form-group">
  <input class="form-control" data-class="search-input" id="focusedInput" placeholder="Type Alphanumeric Character to search" type="text" data-url= <%= contacts_path %> >
</div>

<div class="digit-buttons-container">
  <div class="btn-group btn-group-justified">
    <a href="#" class="btn btn-default" data-class="input-buttons">
      <span class="digit" data-value="1">1<span>
      <p class="text-primary"></p>
    </a>
    <a href="#" class="btn btn-default" data-class="input-buttons">
      <span class="digit" data-value="2">2</span>
      <p class="text-primary">ABC</p>
    </a>
    <a href="#" class="btn btn-default" data-class="input-buttons">
      <span class="digit" data-value="3">3</span>
      <p class="text-primary">DEF</p>
    </a>
  </div>
  <div class="btn-group btn-group-justified">
    <a href="#" class="btn btn-default" data-class="input-buttons">
      <span class="digit" data-value="4">4</span>
      <p class="text-primary">GHI</p>
    </a>
    <a href="#" class="btn btn-default" data-class="input-buttons">
      <span class="digit" data-value="5">5</span>
      <p class="text-primary">JKL</p>
    </a>
    <a href="#" class="btn btn-default" data-class="input-buttons">
      <span class="digit" data-value="5">6</span>
      <p class="text-primary">MNO</p>
    </a>
  </div>
  <div class="btn-group btn-group-justified">
    <a href="#" class="btn btn-default" data-class="input-buttons">
      <span class="digit" data-value="7">7</span>
      <p class="text-primary">PQRS</p>
    </a>
    <a href="#" class="btn btn-default" data-class="input-buttons">
      <span class="digit" data-value="8">8</span>
      <p class="text-primary">TUV</p>
    </a>
    <a href="#" class="btn btn-default" data-class="input-buttons">
      <span class="digit" data-value="9">9</span>
      <p class="text-primary">WXYZ</p>
    </a>
  </div>
  <div class="btn-group btn-group-justified">
    <a href="#" class="btn btn-default" data-class="input-buttons">
      <span class="digit" data-value="*">*</span>
      <p class="text-primary"></p>
    </a>
    <a href="#" class="btn btn-default" data-class="input-buttons">
      <span class="digit" data-value="0">0</span>
      <p class="text-primary">+</p>
    </a>
    <a href="#" class="btn btn-default" data-class="input-buttons">
      <span class="digit" data-value="#">#</span>
      <p class="text-primary"></p>
    </a>
  </div>
</div>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<% if @contacts.present? %>
  <div class="container">
    <table class="table table-striped table-hover col-md-8">
      <thead>
      </thead>
      <tbody data-class="contacts-container">
        <%= render @contacts %>
      </tbody>
    </table>
    <!-- dummy contact container  -->
    <table data-class="dummy-contacts-container">
      <tr class="info text-center hidden" data-class="dummy-row">
        <td><p data-class="contact-name"><a href="#"></a></p>
        <p data-class="contact-number"></p></td>
      </tr>
    </table>
  </div>
<% end %>

<div class="container">
  <%= render partial: 'search_form' %>
</div>
<br>
<div class="text-center">
<%= link_to 'New Contact', new_contact_path, class: 'btn btn-primary'%>
</div>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @contact.number %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %> |
<%= link_to 'Delete', contact_path(@contact), method: :delete, data: { confirm: t(:confirm_delete) } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= yield :footer %>
</body>
</html>